module Pangea
  module Resources
    module AWS
      class IotAnalyticsChannelAttributes < Dry::Struct
        def has_custom_storage?: () -> bool
        def retention_period_days: () -> Integer
        def has_unlimited_retention?: () -> bool
        def storage_type: () -> String
        def estimated_cost_tier: () -> String
      end

      def aws_iot_analytics_channel: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end