# TypeProf 0.21.2

module Pangea
  module Resources
    module AwsPinpointApp
      module Types
        class CampaignHook
          attr_reader lambda_function_name: String?
          attr_reader mode: ("DELIVERY" | "FILTER")?
          attr_reader web_url: String?
        end

        class QuietTime
          attr_reader end: String?
          attr_reader start: String?
        end

        class Limits
          attr_reader daily: Integer?
          attr_reader maximum_duration: Integer?
          attr_reader messages_per_second: Integer?
          attr_reader total: Integer?
        end

        class Attributes
          attr_reader name: String
          attr_reader name_prefix: String?
          attr_reader campaign_hook: CampaignHook?
          attr_reader limits: Limits?
          attr_reader quiet_time: QuietTime?
          attr_reader tags: Hash[String, String]?

          def self.from_dynamic: (Hash[Symbol, untyped] d) -> Attributes
        end

        class Reference
          attr_reader application_id: String
          attr_reader arn: String
          attr_reader name: String
        end
      end

      module Resource
        def self.validate: (Hash[Symbol, untyped] definition) -> Types::Attributes
        def self.defaults: () -> Hash[Symbol, untyped]
        def self.required_attributes: () -> Array[Symbol]
        def self.compute_attributes: (Hash[Symbol, untyped] definition) -> Types::Reference
        
        private
        
        def self.ref: (String | Symbol name, Symbol attribute) -> String
      end
    end
  end
end