# frozen_string_literal: true

module Pangea
  module Resources
    module AWS
      # Create AWS Redshift Subnet Group resource
      def aws_redshift_subnet_group: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end