# frozen_string_literal: true

module Pangea
  module Resources
    module AWS
      # Create AWS Redshift Cluster resource
      def aws_redshift_cluster: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end