# frozen_string_literal: true

module Pangea
  module Resources
    module AWS
      # Create AWS Redshift Snapshot Schedule resource
      def aws_redshift_snapshot_schedule: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end