# RBS type definitions for AWS AppSync Resolver resource

module Pangea
  module Resources
    module AWS
      module Types
        type appsync_resolver_kind = "UNIT" | "PIPELINE"
        type appsync_runtime_name = "APPSYNC_JS"
        type appsync_conflict_detection = "VERSION" | "NONE"
        type appsync_conflict_handler = "OPTIMISTIC_CONCURRENCY" | "LAMBDA" | "AUTOMERGE" | "NONE"

        interface _AppSyncRuntime
          def name: () -> appsync_runtime_name
          def runtime_version: () -> String
        end

        interface _AppSyncPipelineConfig
          def functions: () -> Array[String]
        end

        interface _AppSyncCachingConfig
          def caching_keys?: () -> Array[String]?
          def ttl?: () -> Integer?
        end

        interface _AppSyncSyncConfig
          def conflict_detection?: () -> appsync_conflict_detection?
          def conflict_handler?: () -> appsync_conflict_handler?
          def lambda_conflict_handler_config?: () -> {
            lambda_conflict_handler_arn?: String?
          }?
        end

        class AppSyncResolverAttributes < Dry::Struct
          def self.new: (Hash[Symbol, untyped] attributes) -> instance

          def api_id: () -> String
          def type: () -> String
          def field: () -> String
          def code?: () -> String?
          def data_source?: () -> String?
          def kind?: () -> appsync_resolver_kind?
          def max_batch_size?: () -> Integer?
          def pipeline_config?: () -> _AppSyncPipelineConfig?
          def request_template?: () -> String?
          def response_template?: () -> String?
          def runtime?: () -> _AppSyncRuntime?
          def caching_config?: () -> _AppSyncCachingConfig?
          def sync_config?: () -> _AppSyncSyncConfig?
        end
      end

      # Create an AWS AppSync Resolver
      def aws_appsync_resolver: (
        Symbol name,
        ?api_id: String,
        ?type: String,
        ?field: String,
        ?code: String,
        ?data_source: String,
        ?kind: Types::appsync_resolver_kind,
        ?max_batch_size: Integer,
        ?pipeline_config: {
          functions: Array[String]
        },
        ?request_template: String,
        ?response_template: String,
        ?runtime: {
          name: Types::appsync_runtime_name,
          runtime_version: String
        },
        ?caching_config: {
          ?caching_keys: Array[String],
          ?ttl: Integer
        },
        ?sync_config: {
          ?conflict_detection: Types::appsync_conflict_detection,
          ?conflict_handler: Types::appsync_conflict_handler,
          ?lambda_conflict_handler_config: {
            ?lambda_conflict_handler_arn: String
          }
        }
      ) -> ResourceReference
    end
  end
end