# RBS type definitions for AWS AppSync GraphQL API resource

module Pangea
  module Resources
    module AWS
      module Types
        type appsync_authentication_type = "API_KEY" | "AWS_IAM" | "AMAZON_COGNITO_USER_POOLS" | "OPENID_CONNECT" | "AWS_LAMBDA"
        type appsync_field_log_level = "NONE" | "ERROR" | "ALL"
        type appsync_resolver_kind = "UNIT" | "PIPELINE"
        type appsync_api_type = "GRAPHQL" | "MERGED"
        type appsync_introspection = "ENABLED" | "DISABLED"
        type appsync_visibility = "GLOBAL" | "PRIVATE"
        type appsync_default_action = "ALLOW" | "DENY"

        interface _AppSyncRuntime
          def name: () -> ("APPSYNC_JS")
          def runtime_version: () -> String
        end

        interface _AppSyncLogConfig
          def cloudwatch_logs_role_arn: () -> String
          def field_log_level: () -> appsync_field_log_level
          def exclude_verbose_content?: () -> bool?
        end

        interface _AppSyncUserPoolConfig
          def app_id_client_regex?: () -> String?
          def aws_region?: () -> String?
          def default_action?: () -> appsync_default_action?
          def user_pool_id: () -> String
        end

        interface _AppSyncOpenIdConnectConfig
          def auth_ttl?: () -> Integer?
          def client_id?: () -> String?
          def iat_ttl?: () -> Integer?
          def issuer: () -> String
        end

        interface _AppSyncLambdaAuthorizerConfig
          def authorizer_result_ttl_in_seconds?: () -> Integer?
          def authorizer_uri: () -> String
          def identity_validation_expression?: () -> String?
        end

        interface _AppSyncAdditionalAuthenticationProvider
          def authentication_type: () -> appsync_authentication_type
          def user_pool_config?: () -> _AppSyncUserPoolConfig?
          def openid_connect_config?: () -> _AppSyncOpenIdConnectConfig?
          def lambda_authorizer_config?: () -> _AppSyncLambdaAuthorizerConfig?
        end

        class AppSyncGraphqlApiAttributes < Dry::Struct
          def self.new: (Hash[Symbol, untyped] attributes) -> instance

          def name: () -> String
          def authentication_type: () -> appsync_authentication_type
          def additional_authentication_providers?: () -> Array[_AppSyncAdditionalAuthenticationProvider]?
          def api_type?: () -> appsync_api_type?
          def introspection_config?: () -> appsync_introspection?
          def lambda_authorizer_config?: () -> _AppSyncLambdaAuthorizerConfig?
          def log_config?: () -> _AppSyncLogConfig?
          def merged_api_execution_role_arn?: () -> String?
          def openid_connect_config?: () -> _AppSyncOpenIdConnectConfig?
          def query_depth_limit?: () -> Integer?
          def resolver_count_limit?: () -> Integer?
          def schema?: () -> String?
          def user_pool_config?: () -> _AppSyncUserPoolConfig?
          def visibility?: () -> appsync_visibility?
          def xray_enabled?: () -> bool?
          def tags?: () -> Hash[Symbol, String]?
        end
      end

      # Create an AWS AppSync GraphQL API
      def aws_appsync_graphql_api: (
        Symbol name,
        ?name: String,
        ?authentication_type: Types::appsync_authentication_type,
        ?additional_authentication_providers: Array[{
          authentication_type: Types::appsync_authentication_type,
          ?user_pool_config: {
            user_pool_id: String,
            ?app_id_client_regex: String,
            ?aws_region: String,
            ?default_action: Types::appsync_default_action
          },
          ?openid_connect_config: {
            issuer: String,
            ?auth_ttl: Integer,
            ?client_id: String,
            ?iat_ttl: Integer
          },
          ?lambda_authorizer_config: {
            authorizer_uri: String,
            ?authorizer_result_ttl_in_seconds: Integer,
            ?identity_validation_expression: String
          }
        }],
        ?api_type: Types::appsync_api_type,
        ?introspection_config: Types::appsync_introspection,
        ?lambda_authorizer_config: {
          authorizer_uri: String,
          ?authorizer_result_ttl_in_seconds: Integer,
          ?identity_validation_expression: String
        },
        ?log_config: {
          cloudwatch_logs_role_arn: String,
          field_log_level: Types::appsync_field_log_level,
          ?exclude_verbose_content: bool
        },
        ?merged_api_execution_role_arn: String,
        ?openid_connect_config: {
          issuer: String,
          ?auth_ttl: Integer,
          ?client_id: String,
          ?iat_ttl: Integer
        },
        ?query_depth_limit: Integer,
        ?resolver_count_limit: Integer,
        ?schema: String,
        ?user_pool_config: {
          user_pool_id: String,
          ?app_id_client_regex: String,
          ?aws_region: String,
          ?default_action: Types::appsync_default_action
        },
        ?visibility: Types::appsync_visibility,
        ?xray_enabled: bool,
        ?tags: Hash[Symbol, String]
      ) -> ResourceReference
    end
  end
end