# frozen_string_literal: true

module Pangea
  module Resources
    module AWS
      # Create AWS Config Config Rule resource
      def aws_config_config_rule: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end