# frozen_string_literal: true

module Pangea
  module Resources
    module AWS
      # Create AWS CodePipeline resource
      def aws_codepipeline: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end