# TypeProf 0.21.2

module Pangea
  module Resources
    module AwsGameliftFleet
      module Types
        class IpPermission
          attr_reader from_port: Integer
          attr_reader to_port: Integer
          attr_reader ip_range: String
          attr_reader protocol: "TCP" | "UDP"
        end

        class ServerProcess
          attr_reader concurrent_executions: Integer
          attr_reader launch_path: String
          attr_reader parameters: String?
        end

        class RuntimeConfiguration
          attr_reader game_session_activation_timeout_seconds: Integer?
          attr_reader max_concurrent_game_session_activations: Integer?
          attr_reader server_process: Array[ServerProcess]?
        end

        class ResourceCreationLimitPolicy
          attr_reader new_game_sessions_per_creator: Integer?
          attr_reader policy_period_in_minutes: Integer?
        end

        class CertificateConfiguration
          attr_reader certificate_type: "DISABLED" | "GENERATED"
        end

        class Attributes
          attr_reader name: String
          attr_reader build_id: String?
          attr_reader script_id: String?
          attr_reader ec2_instance_type: String
          attr_reader description: String?
          attr_reader ec2_inbound_permission: Array[IpPermission]?
          attr_reader fleet_type: ("ON_DEMAND" | "SPOT")?
          attr_reader instance_role_arn: String?
          attr_reader certificate_configuration: CertificateConfiguration?
          attr_reader metric_groups: Array[String]?
          attr_reader new_game_session_protection_policy: ("NoProtection" | "FullProtection")?
          attr_reader resource_creation_limit_policy: ResourceCreationLimitPolicy?
          attr_reader runtime_configuration: RuntimeConfiguration?
          attr_reader peer_vpc_aws_account_id: String?
          attr_reader peer_vpc_id: String?
          attr_reader tags: Hash[String, String]?
          attr_reader compute_type: ("EC2" | "ANYWHERE")?
          attr_reader anywhere_configuration: Hash[untyped, untyped]?
          attr_reader desired_ec2_instances: Integer?
          attr_reader min_size: Integer?
          attr_reader max_size: Integer?

          def self.from_dynamic: (Hash[Symbol, untyped] d) -> Attributes
        end

        class Reference
          attr_reader id: String
          attr_reader arn: String
          attr_reader build_arn: String
          attr_reader creation_time: String
          attr_reader operating_system: String
          attr_reader status: String
          attr_reader log_paths: Array[String]
        end
      end

      module Resource
        def self.validate: (Hash[Symbol, untyped] definition) -> Types::Attributes
        def self.defaults: () -> Hash[Symbol, untyped]
        def self.required_attributes: () -> Array[Symbol]
        def self.compute_attributes: (Hash[Symbol, untyped] definition) -> Types::Reference
        
        private
        
        def self.ref: (String | Symbol name, Symbol attribute) -> String
      end
    end
  end
end