# RBS type definitions for AWS GuardDuty Member resource

module Pangea
  module Resources
    module AWS
      module Types
        class GuardDutyMemberAttributes < Dry::Struct
          def self.new: (Hash[Symbol, untyped] attributes) -> instance

          def account_id: () -> String
          def detector_id: () -> String
          def email: () -> String
          def invite: () -> bool
          def invitation_message?: () -> String?
          def disable_email_notification: () -> bool

          def will_send_invitation?: () -> bool
          def invitation_enabled?: () -> bool
        end
      end

      # Create an AWS GuardDuty Member
      def aws_guardduty_member: (
        Symbol name,
        ?account_id: String,
        ?detector_id: String,
        ?email: String,
        ?invite: bool,
        ?invitation_message: String,
        ?disable_email_notification: bool
      ) -> ResourceReference
    end
  end
end