# frozen_string_literal: true

module Pangea
  module Resources
    module AWS
      # Create AWS CodeDeploy Deployment Configuration resource
      def aws_codedeploy_deployment_config: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end