# frozen_string_literal: true

module Pangea
  module Resources
    module AWS
      # Create AWS Athena Database resource
      def aws_athena_database: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end