module Pangea
  module Resources
    module AWS
      class IotTopicRuleDestinationAttributes < Dry::Struct
        def vpc_subnet_count: () -> Integer
        def security_group_count: () -> Integer
        def is_multi_az?: () -> bool
      end

      def aws_iot_topic_rule_destination: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end