# frozen_string_literal: true

module Pangea
  module Resources
    module AWS
      # Create AWS CloudTrail resource
      def aws_cloudtrail: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end