# frozen_string_literal: true

module Pangea
  module Resources
    module AWS
      # Create AWS Athena Named Query resource
      def aws_athena_named_query: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end