# frozen_string_literal: true

module Pangea
  module Resources
    module AWS
      # Create AWS CodeBuild Project resource
      def aws_codebuild_project: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end