# frozen_string_literal: true

module Pangea
  module Resources
    module AWS
      # Create AWS Organizations Account resource
      def aws_organizations_account: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end