# frozen_string_literal: true

module Pangea
  module Resources
    module AWS
      # Create AWS Config Configuration Recorder resource
      def aws_config_configuration_recorder: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end