# frozen_string_literal: true

# Load all AWS resource implementations
require 'pangea/resources/base'
require 'pangea/resources/aws_vpc/resource'
require 'pangea/resources/aws_subnet/resource'
require 'pangea/resources/aws_security_group/resource'
require 'pangea/resources/aws_instance/resource'
require 'pangea/resources/aws_internet_gateway/resource'
require 'pangea/resources/aws_route_table/resource'
require 'pangea/resources/aws_nat_gateway/resource'
require 'pangea/resources/aws_lb/resource'
require 'pangea/resources/aws_lb_listener/resource'
require 'pangea/resources/aws_lb_listener_rule/resource'
require 'pangea/resources/aws_lb_listener_certificate/resource'
require 'pangea/resources/aws_lb_target_group_attachment/resource'
require 'pangea/resources/aws_launch_template/resource'
require 'pangea/resources/aws_autoscaling_group/resource'
require 'pangea/resources/aws_lb_target_group/resource'
require 'pangea/resources/aws_autoscaling_attachment/resource'
require 'pangea/resources/aws_autoscaling_policy/resource'
require 'pangea/resources/aws_autoscaling_schedule/resource'
require 'pangea/resources/aws_autoscaling_lifecycle_hook/resource'
require 'pangea/resources/aws_autoscaling_notification/resource'
require 'pangea/resources/aws_autoscaling_tag/resource'
require 'pangea/resources/aws_cloudwatch_metric_alarm/resource'
require 'pangea/resources/aws_cloudwatch_log_group/resource'
require 'pangea/resources/aws_cloudwatch_log_stream/resource'
require 'pangea/resources/aws_cloudwatch_dashboard/resource'
require 'pangea/resources/aws_s3_bucket/resource'
require 'pangea/resources/aws_s3_bucket_policy/resource'
require 'pangea/resources/aws_s3_bucket_versioning/resource'
require 'pangea/resources/aws_s3_bucket_encryption/resource'
require 'pangea/resources/aws_s3_bucket_public_access_block/resource'
require 'pangea/resources/aws_s3_object/resource'
require 'pangea/resources/aws_s3_bucket_lifecycle_configuration/resource'
require 'pangea/resources/aws_s3_bucket_cors_configuration/resource'
require 'pangea/resources/aws_s3_bucket_website_configuration/resource'
require 'pangea/resources/aws_iam_role/resource'
require 'pangea/resources/aws_iam_policy/resource'
require 'pangea/resources/aws_iam_role_policy_attachment/resource'
require 'pangea/resources/aws_iam_user/resource'
require 'pangea/resources/aws_iam_group/resource'
require 'pangea/resources/aws_db_instance/resource'
require 'pangea/resources/aws_db_subnet_group/resource'
require 'pangea/resources/aws_db_parameter_group/resource'
require 'pangea/resources/aws_rds_cluster/resource'
require 'pangea/resources/aws_rds_cluster_instance/resource'
require 'pangea/resources/aws_rds_cluster_endpoint/resource'
require 'pangea/resources/aws_rds_cluster_parameter_group/resource'
require 'pangea/resources/aws_rds_global_cluster/resource'
require 'pangea/resources/aws_rds_proxy/resource'
require 'pangea/resources/aws_rds_proxy_default_target_group/resource'
require 'pangea/resources/aws_rds_proxy_target/resource'
require 'pangea/resources/aws_db_snapshot/resource'
require 'pangea/resources/aws_db_cluster_snapshot/resource'
require 'pangea/resources/aws_route_table_association/resource'
require 'pangea/resources/aws_vpc_endpoint/resource'
require 'pangea/resources/aws_vpc_endpoint_service/resource'
require 'pangea/resources/aws_vpc_peering_connection/resource'
require 'pangea/resources/aws_vpc_peering_connection_accepter/resource'
require 'pangea/resources/aws_vpn_connection/resource'
require 'pangea/resources/aws_vpn_gateway/resource'
require 'pangea/resources/aws_customer_gateway/resource'
require 'pangea/resources/aws_eip/resource'
require 'pangea/resources/aws_eip_association/resource'
require 'pangea/resources/aws_route/resource'
require 'pangea/resources/aws_network_interface/resource'
require 'pangea/resources/aws_network_acl/resource'
require 'pangea/resources/aws_network_acl_rule/resource'
require 'pangea/resources/aws_key_pair/resource'
require 'pangea/resources/aws_ebs_volume/resource'
require 'pangea/resources/aws_volume_attachment/resource'
require 'pangea/resources/aws_ami/resource'
require 'pangea/resources/aws_efs_file_system/resource'
require 'pangea/resources/aws_efs_mount_target/resource'
require 'pangea/resources/aws_efs_access_point/resource'
require 'pangea/resources/aws_ecs_cluster/resource'
require 'pangea/resources/aws_ecs_task_definition/resource'
require 'pangea/resources/aws_ecs_service/resource'
require 'pangea/resources/aws_ecs_cluster_capacity_providers/resource'
require 'pangea/resources/aws_lambda_function/resource'
require 'pangea/resources/aws_lambda_permission/resource'
require 'pangea/resources/aws_lambda_event_source_mapping/resource'
require 'pangea/resources/aws_lambda_layer_version/resource'
require 'pangea/resources/aws_api_gateway_rest_api/resource'
require 'pangea/resources/aws_api_gateway_resource/resource'
require 'pangea/resources/aws_api_gateway_method/resource'
require 'pangea/resources/aws_api_gateway_deployment/resource'
require 'pangea/resources/aws_api_gateway_stage/resource'
require 'pangea/resources/aws_sqs_queue/resource'
require 'pangea/resources/aws_sqs_queue_policy/resource'
require 'pangea/resources/aws_sns_topic/resource'
require 'pangea/resources/aws_sns_subscription/resource'
require 'pangea/resources/aws_eks_cluster/resource'
require 'pangea/resources/aws_eks_node_group/resource'
require 'pangea/resources/aws_eks_addon/resource'
require 'pangea/resources/aws_eks_fargate_profile/resource'
require 'pangea/resources/aws_acm_certificate/resource'
require 'pangea/resources/aws_acm_certificate_validation/resource'
require 'pangea/resources/aws_secretsmanager_secret/resource'
require 'pangea/resources/aws_secretsmanager_secret_version/resource'
require 'pangea/resources/aws_kms_key/resource'
require 'pangea/resources/aws_kms_alias/resource'
require 'pangea/resources/aws_elasticache_cluster/resource'
require 'pangea/resources/aws_elasticache_subnet_group/resource'
require 'pangea/resources/aws_elasticache_parameter_group/resource'
require 'pangea/resources/aws_route53_zone/resource'
require 'pangea/resources/aws_route53_record/resource'
require 'pangea/resources/aws_route53_health_check/resource'
require 'pangea/resources/aws_dynamodb_table/resource'
require 'pangea/resources/aws_dynamodb_global_table/resource'
require 'pangea/resources/aws_eventbridge_bus/resource'
require 'pangea/resources/aws_eventbridge_rule/resource'
require 'pangea/resources/aws_eventbridge_target/resource'
require 'pangea/resources/aws_sfn_state_machine/resource'
require 'pangea/resources/aws_sfn_activity/resource'
require 'pangea/resources/aws_batch_compute_environment/resource'
require 'pangea/resources/aws_batch_job_queue/resource'
require 'pangea/resources/aws_batch_job_definition/resource'
require 'pangea/resources/aws_cloudformation_stack/resource'
require 'pangea/resources/aws_cloudformation_stack_set/resource'
require 'pangea/resources/aws_ssm_parameter/resource'
require 'pangea/resources/aws_ssm_document/resource'
require 'pangea/resources/aws_ssm_maintenance_window/resource'
require 'pangea/resources/aws_ssm_patch_baseline/resource'
require 'pangea/resources/aws_ec2_transit_gateway/resource'
require 'pangea/resources/aws_ec2_transit_gateway_vpc_attachment/resource'
require 'pangea/resources/aws_ec2_transit_gateway_route_table/resource'
require 'pangea/resources/aws_ec2_transit_gateway_route/resource'
require 'pangea/resources/aws_ec2_transit_gateway_route_table_association/resource'
require 'pangea/resources/aws_ec2_transit_gateway_route_table_propagation/resource'
require 'pangea/resources/aws_kinesis_stream/resource'
require 'pangea/resources/aws_kinesis_firehose_delivery_stream/resource'
require 'pangea/resources/aws_kinesis_analytics_application/resource'
require 'pangea/resources/aws_kinesis_video_stream/resource'
require 'pangea/resources/aws_glue_catalog_database/resource'
require 'pangea/resources/aws_glue_catalog_table/resource'
require 'pangea/resources/aws_glue_job/resource'
require 'pangea/resources/aws_glue_trigger/resource'
require 'pangea/resources/aws_emr_cluster/resource'
require 'pangea/resources/aws_emr_instance_group/resource'
require 'pangea/resources/aws_emr_step/resource'
require 'pangea/resources/aws_athena_database/resource'
require 'pangea/resources/aws_athena_workgroup/resource'
require 'pangea/resources/aws_athena_named_query/resource'
require 'pangea/resources/aws_redshift_cluster/resource'
require 'pangea/resources/aws_redshift_subnet_group/resource'
require 'pangea/resources/aws_redshift_parameter_group/resource'
require 'pangea/resources/aws_redshift_snapshot_schedule/resource'
require 'pangea/resources/aws_codecommit_repository/resource'
require 'pangea/resources/aws_codebuild_project/resource'
require 'pangea/resources/aws_codedeploy_application/resource'
require 'pangea/resources/aws_codedeploy_deployment_group/resource'
require 'pangea/resources/aws_codedeploy_deployment_config/resource'
require 'pangea/resources/aws_codepipeline/resource'
require 'pangea/resources/aws_codepipeline_webhook/resource'
require 'pangea/resources/aws_cloudwatch_composite_alarm/resource'
require 'pangea/resources/aws_cloudwatch_log_destination/resource'
require 'pangea/resources/aws_cloudwatch_log_destination_policy/resource'
require 'pangea/resources/aws_cloudwatch_log_metric_filter/resource'
require 'pangea/resources/aws_cloudwatch_log_subscription_filter/resource'
require 'pangea/resources/aws_cloudwatch_event_rule/resource'
require 'pangea/resources/aws_cloudwatch_event_target/resource'
require 'pangea/resources/aws_appsync_graphql_api/resource'
require 'pangea/resources/aws_appsync_datasource/resource'
require 'pangea/resources/aws_appsync_resolver/resource'
require 'pangea/resources/aws_ses_domain_identity/resource'
require 'pangea/resources/aws_ses_email_identity/resource'
require 'pangea/resources/aws_ses_configuration_set/resource'
require 'pangea/resources/aws_mq_broker/resource'
require 'pangea/resources/aws_mq_configuration/resource'

# AWS Security Services
require 'pangea/resources/aws_wafv2_web_acl/resource'
require 'pangea/resources/aws_wafv2_rule_group/resource'
require 'pangea/resources/aws_wafv2_ip_set/resource'
require 'pangea/resources/aws_guardduty_detector/resource'
require 'pangea/resources/aws_guardduty_member/resource'
require 'pangea/resources/aws_securityhub_account/resource'
require 'pangea/resources/aws_inspector2_enabler/resource'

# AWS Governance and Compliance Services
require 'pangea/resources/aws_config_configuration_recorder/resource'
require 'pangea/resources/aws_config_delivery_channel/resource'
require 'pangea/resources/aws_config_config_rule/resource'
require 'pangea/resources/aws_config_remediation_configuration/resource'
require 'pangea/resources/aws_cloudtrail/resource'
require 'pangea/resources/aws_cloudtrail_event_data_store/resource'
require 'pangea/resources/aws_organizations_organization/resource'
require 'pangea/resources/aws_organizations_account/resource'

# AWS SageMaker Machine Learning Services
require 'pangea/resources/aws_sagemaker_domain/resource'
require 'pangea/resources/aws_sagemaker_user_profile/resource'
require 'pangea/resources/aws_sagemaker_notebook_instance/resource'
require 'pangea/resources/aws_sagemaker_model/resource'
require 'pangea/resources/aws_sagemaker_endpoint_configuration/resource'
require 'pangea/resources/aws_sagemaker_endpoint/resource'
require 'pangea/resources/aws_sagemaker_training_job/resource'
require 'pangea/resources/aws_sagemaker_processing_job/resource'
require 'pangea/resources/aws_sagemaker_pipeline/resource'
require 'pangea/resources/aws_sagemaker_feature_group/resource'

# AWS Developer Services - Container and Artifact Management
require 'pangea/resources/aws_ecr_repository/resource'
require 'pangea/resources/aws_ecr_repository_policy/resource'
require 'pangea/resources/aws_ecr_lifecycle_policy/resource'
require 'pangea/resources/aws_ecr_replication_configuration/resource'
require 'pangea/resources/aws_codeartifact_domain/resource'
require 'pangea/resources/aws_codeartifact_repository/resource'
require 'pangea/resources/aws_codestar_connection/resource'

# Advanced S3 Features
require 'pangea/resources/aws_s3_bucket_notification/resource'
require 'pangea/resources/aws_s3_bucket_inventory/resource'
require 'pangea/resources/aws_s3_bucket_replication_configuration/resource'
require 'pangea/resources/aws_s3_bucket_object_lock_configuration/resource'

# CloudFront CDN Resources
require 'pangea/resources/aws_cloudfront_distribution/resource'
require 'pangea/resources/aws_cloudfront_origin_access_control/resource'
require 'pangea/resources/aws_cloudfront_cache_policy/resource'
require 'pangea/resources/aws_cloudfront_origin_request_policy/resource'

# AWS IoT Core Resources
require 'pangea/resources/aws_iot_thing/resource'
require 'pangea/resources/aws_iot_thing_type/resource'
require 'pangea/resources/aws_iot_certificate/resource'
require 'pangea/resources/aws_iot_policy/resource'
require 'pangea/resources/aws_iot_topic_rule/resource'
require 'pangea/resources/aws_iot_topic_rule_destination/resource'
require 'pangea/resources/aws_iot_security_profile/resource'
require 'pangea/resources/aws_iot_device_defender_security_profile/resource'
require 'pangea/resources/aws_iot_analytics_channel/resource'
require 'pangea/resources/aws_iot_analytics_datastore/resource'

# AWS Cost Management and Billing Resources
require 'pangea/resources/aws_budgets_budget/resource'
require 'pangea/resources/aws_budgets_budget_action/resource'
require 'pangea/resources/aws_ce_cost_category/resource'
require 'pangea/resources/aws_ce_anomaly_detector/resource'
require 'pangea/resources/aws_ce_anomaly_subscription/resource'
require 'pangea/resources/aws_cur_report_definition/resource'
require 'pangea/resources/aws_billing_service_account/resource'

# AWS Cognito Identity and User Management Resources
require 'pangea/resources/aws_cognito_user_pool/resource'
require 'pangea/resources/aws_cognito_user_pool_client/resource'
require 'pangea/resources/aws_cognito_user_pool_domain/resource'
require 'pangea/resources/aws_cognito_identity_pool/resource'
require 'pangea/resources/aws_cognito_identity_provider/resource'
require 'pangea/resources/aws_cognito_user_group/resource'
require 'pangea/resources/aws_cognito_user/resource'

# AWS Media Services
require 'pangea/resources/aws_media_live_channel/resource'
require 'pangea/resources/aws_media_live_input/resource'
require 'pangea/resources/aws_media_package_channel/resource'
require 'pangea/resources/aws_media_package_origin_endpoint/resource'
require 'pangea/resources/aws_media_store_container/resource'
require 'pangea/resources/aws_media_convert_queue/resource'
require 'pangea/resources/aws_elemental_data_plane_channel/resource'

# AWS GameLift and Mobile Gaming Services
require 'pangea/resources/aws_gamelift_fleet/resource'
require 'pangea/resources/aws_gamelift_build/resource'
require 'pangea/resources/aws_gamelift_alias/resource'
require 'pangea/resources/aws_gamelift_game_session_queue/resource'
require 'pangea/resources/aws_gamelift_matchmaking_configuration/resource'
require 'pangea/resources/aws_device_farm_project/resource'
require 'pangea/resources/aws_pinpoint_app/resource'
require 'pangea/resources/aws_mobile_analytics_app/resource'

# AWS WorkSpaces and Enterprise Desktop Services
require 'pangea/resources/aws_workspaces_workspace/resource'
require 'pangea/resources/aws_workspaces_directory/resource'
require 'pangea/resources/aws_workspaces_bundle/resource'
require 'pangea/resources/aws_workspaces_ip_group/resource'
require 'pangea/resources/aws_appstream_fleet/resource'
require 'pangea/resources/aws_appstream_stack/resource'
require 'pangea/resources/aws_appstream_image_builder/resource'
require 'pangea/resources/aws_directory_service_directory/resource'

# AWS Quantum Computing and Blockchain Services
require 'pangea/resources/aws_braket_quantum_task/resource'
require 'pangea/resources/aws_braket_device/resource'
require 'pangea/resources/aws_braket_job/resource'
require 'pangea/resources/aws_braket_job_queue/resource'
require 'pangea/resources/aws_braket_local_simulator/resource'
require 'pangea/resources/aws_braket_device_capabilities/resource'
require 'pangea/resources/aws_managedblockchain_network/resource'
require 'pangea/resources/aws_managedblockchain_node/resource'
require 'pangea/resources/aws_managedblockchain_member/resource'
require 'pangea/resources/aws_managedblockchain_accessor/resource'
require 'pangea/resources/aws_managedblockchain_ethereum_node/resource'
require 'pangea/resources/aws_blockchain_query/resource'
require 'pangea/resources/aws_blockchain_token_balance/resource'
require 'pangea/resources/aws_qldb_ledger/resource'
require 'pangea/resources/aws_qldb_stream/resource'

# AWS Service Catalog
require 'pangea/resources/aws/servicecatalog/portfolio_resource'
require 'pangea/resources/aws/servicecatalog/product_resource'
require 'pangea/resources/aws/servicecatalog/constraint_resource'
require 'pangea/resources/aws/servicecatalog/principal_portfolio_association_resource'
require 'pangea/resources/aws/servicecatalog/product_portfolio_association_resource'
require 'pangea/resources/aws/servicecatalog/provisioned_product_resource'
require 'pangea/resources/aws/servicecatalog/tag_option_resource'
require 'pangea/resources/aws/servicecatalog/tag_option_resource_association_resource'

# AWS Control Tower
require 'pangea/resources/aws/controltower/control_resource'
require 'pangea/resources/aws/controltower/landing_zone_resource'

# AWS Well-Architected Tool
require 'pangea/resources/aws/wellarchitected/workload_resource'

# AWS Systems Manager (Additional Resources)
require 'pangea/resources/aws/ssm/maintenance_window_task_resource'
require 'pangea/resources/aws/ssm/maintenance_window_target_resource'

# AWS Application Discovery Service
require 'pangea/resources/aws/applicationdiscoveryservice/application_resource'

# AWS Migration Hub
require 'pangea/resources/aws/migrationhub/progress_update_stream_resource'

module Pangea
  module Resources
    # AWS resource functions module that includes all AWS resource implementations
    # Each resource is implemented in its own directory under aws_*/
    module AWS
      include Base
    end
  end
end