# TypeProf 0.21.9

module Pangea
  module Resources
    module AWS
      module ServiceCatalog
        class ProvisionedProductResource < Pangea::Resources::Base
          def validate: () -> void
          def arn: () -> String
          def id: () -> String
          def cloudformation_stack_id: () -> String
          def status: () -> String
          def outputs: () -> String
        end
      end
    end
  end
end