# TypeProf 0.21.9

module Pangea
  module Resources
    module AWS
      module ServiceCatalog
        class TagOptionResourceAssociationResource < Pangea::Resources::Base
          def validate: () -> void
          def id: () -> String
        end
      end
    end
  end
end