module Pangea
  module Resources
    module AWS
      # AWS Lightsail instance resource function
      #
      # @param name [Symbol] The resource name
      # @param attributes [Hash] Instance attributes
      # @return [ResourceReference] Reference object with outputs
      def aws_lightsail_instance: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end