module Pangea
  module Resources
    module AWS
      # Aws Ec2 Local Gateway resource function
      #
      # @param name [Symbol] The resource name
      # @param attributes [Hash] Resource attributes
      # @return [ResourceReference] Reference object with outputs
      def aws_ec2_local_gateway: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end
