module Pangea
  module Resources
    module AWS
      # Aws Outposts Supported Hardware Type resource function
      #
      # @param name [Symbol] The resource name
      # @param attributes [Hash] Resource attributes
      # @return [ResourceReference] Reference object with outputs
      def aws_outposts_supported_hardware_type: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end
