module Pangea
  module Resources
    module AWS
      # Aws Datasync On Snow Location resource function
      #
      # @param name [Symbol] The resource name
      # @param attributes [Hash] Resource attributes
      # @return [ResourceReference] Reference object with outputs
      def aws_datasync_on_snow_location: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end
