module Pangea
  module Resources
    module AWS
      # AWS Outposts site resource function
      #
      # @param name [Symbol] The resource name
      # @param attributes [Hash] Site attributes
      # @return [ResourceReference] Reference object with outputs
      def aws_outposts_site: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end