module Pangea
  module Resources
    module AWS
      # AWS Lightsail load balancer resource function
      #
      # @param name [Symbol] The resource name
      # @param attributes [Hash] Load balancer attributes
      # @return [ResourceReference] Reference object with outputs
      def aws_lightsail_load_balancer: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end