module Pangea
  module Resources
    module AWS
      # AWS Outposts outpost resource function
      #
      # @param name [Symbol] The resource name
      # @param attributes [Hash] Outpost attributes
      # @return [ResourceReference] Reference object with outputs
      def aws_outposts_outpost: (Symbol name, Hash[Symbol, untyped] attributes) -> ResourceReference
    end
  end
end