# TypeProf 0.21.9

module Pangea
  module Resources
    module AWS
      module SSM
        class MaintenanceWindowTaskResource < Pangea::Resources::Base
          def validate: () -> void
          def task_id: () -> String
          def window_task_id: () -> String
        end
      end
    end
  end
end