# TypeProf 0.21.9

module Pangea
  module Resources
    module AWS
      module SSM
        class MaintenanceWindowTargetResource < Pangea::Resources::Base
          def validate: () -> void
          def target_id: () -> String
          def window_target_id: () -> String
        end
      end
    end
  end
end