name: Question
description: Ask a question about Pangea
labels: ["question", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please check the documentation first.
        
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to accomplish?
      
  - type: textarea
    id: tried
    attributes:
      label: What I've Tried
      description: What have you already attempted?
      
  - type: checkboxes
    id: docs
    attributes:
      label: Documentation
      options:
        - label: I have checked the README
        - label: I have checked the examples directory
        - label: I have searched existing issues
        
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant details