# TypeProf 0.21.9

module Pangea
  module Resources
    module AWS
      module MigrationHub
        class ProgressUpdateStreamResource < Pangea::Resources::Base
          def validate: () -> void
          def progress_update_stream_name: () -> String
        end
      end
    end
  end
end