# TypeProf 0.21.9

module Pangea
  module Resources
    module AWS
      module ApplicationDiscoveryService
        class ApplicationResource < Pangea::Resources::Base
          def validate: () -> void
          def application_id: () -> String
          def arn: () -> String
        end
      end
    end
  end
end