# TypeProf 0.21.9

module Pangea
  module Resources
    module AWS
      module ControlTower
        class LandingZoneResource < Pangea::Resources::Base
          def validate: () -> void
          def arn: () -> String
          def id: () -> String
          def status: () -> String
          def latest_available_version: () -> String
          def drift_status: () -> String
        end
      end
    end
  end
end