#!/usr/bin/env ruby
# frozen_string_literal: true
# Copyright 2025 The Pangea Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# require 'bundler/setup'  # Commented out to avoid bundler dependency issues
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'pangea'
require 'pangea/cli/application'

# Set up beautiful error handling
begin
  Pangea::CLI::Application.new.run
rescue Interrupt
  puts "\n\nInterrupted. Exiting gracefully..."
  exit 0
rescue StandardError => e
  if ENV['DEBUG']
    raise e
  else
    puts "\nError: #{e.message}"
    puts "\nRun with DEBUG=1 for full backtrace"
    exit 1
  end
end